version: "3.0"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - clean-alta:/var/opt/mssql
    container_name: ALTACleanDB
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit_mq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    hostname: rabbitmq_storage

volumes:
  clean-alta:
#    driver: local
  rabbitmq-data:
